---
  phone-weights-path:       "configs/phone_weights_trivial.yaml"
  folds:                    2
  epochs:                   10
  layers:                   1
  learning-rate:            0.005
  batch-size:               4
  use-dropout:              true
  checkpoint-step:          2
  dropout-p:                0.4
  batchnorm:                "last"
  norm-per-phone-and-class: false
  use-clipping:             false
  use-multi-process:        false
  phones-list-path:         "phones/kaldi/phones-list.txt"
  libri-chain-txt-path:     "librispeech_models/exp/chain_cleaned/tdnn_1d_sp/final.txt"
  data-dir:                 "data/"