---
  AA:    1
  AE:    1
  AH:    1
  AO:    1
  AW:    0
  AY:    1
  B:    1
  CH:    0
  D:    1
  DH:    0
  EH:    1
  ER:    1
  EY:    1
  F:    0
  G:    1
  HH:    1
  IH:    1
  IY:    1
  JH:    1
  K:    1
  L:    0
  M:    0
  N:    0
  NG:    1
  OW:    1
  OY:    0
  P:    1
  R:    1
  S:    0
  SH:    0
  T:    1
  TH:    1
  UH:    1
  UW:    0
  V:    1
  W:    0
  Y:    0
  Z:    1
  ZH:    1
