---
  phone-weights-path:       "configs/phone_weights_50.yaml"
  folds:                    6
  epochs:                   600
  swa_epochs:               0
  layers:                   1
  scheduler:               "StepLR(optimizer, 10, gamma=0.9, last_epoch=-1, verbose=True)"
  learning-rate:            0.01
  batch-size:               32
  use-dropout:              false
  checkpoint-step:          25
  dropout-p:                0.0
  batchnorm:                "none"
  norm-per-phone-and-class: false
  loss-per-phone:           true
  summarize:                "sum"
  use-clipping:             false
  use-multi-process:        false
  phones-list-path:         "phones/kaldi/phones-list.txt"
  libri-chain-txt-path:     "librispeech_models/exp/chain_cleaned/tdnn_1d_sp/final.txt"
  data-dir:                 "data/"